### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by AkshayJainG** [linkedin/qark#12]
:app:mergeDebugResources
Error: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/root/Downloads/qark-master/android-sdk_r24.3.4-linux/android-sdk-linux/build-tools/21.1.2/aapt''
:app:mergeDebugResources FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:mergeDebugResources'.
  
  > Error: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/root/Downloads/qark-master/android-sdk_r24.3.4-linux/android-sdk-linux/build-tools/21.1.2/aapt''
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by SecBro1** [comment]
Akshay, we'll take a look at this. Did you by chance have Android Studio previously installed? If so, did you customize the gradle settings? I ask because it looks like something I've seen when I had a customized gradle setup with a previous install on my computer. 

Also, could you please confirm you have this issue when building an exploit APK for the sample code in the /sampleApps directory?

Lastly, any additional information you can provide regarding operating system type and version and which app you had issues with would be appreciated.

**Comment by AkshayJainG** [comment]
It was newly installed kali Linux 2.0 and i didn't had Android studio on
it.

I am facing this problem with almost all the apps which I am trying to scan
through QARK

Yeah this issue comes when I am trying to build exploit apk

**Comment by davinerd** [comment]
related to this: when a build fails, it still asks you to install the apk to the device (not sure what it tries to install though).
Would be nice to have a 'retry' option instead, so we can investigate why it failed and fix it.

**Comment by AkshayJainG** [comment]
This issue should be closed because it happens only with an particular app.

**Comment by n0x00** [comment]
I'm having the same issue on the goat sample app and all other apps,would love to get it working, even if there was a fully working virtual image / docker ... or a fix so i can run this on my mac

**Comment by PaulSec** [comment]
Would be nice to get a fully working Docker image for Qark.

**Comment by tushardalvi** [comment]
We believe this issue is now resolved. Please let us know if this is still problematic and we will address it asap. A Docker release is coming shortly.
