### ISSUE TITLE
SCA process stuck and never ends

### ISSUE THREAD

**Issue by christopher-wiko** [linkedin/qark#148]
When I'm running the following command, the **SCA** (Static Code Analysis) stuck and never ends...

`$ python -v qarkMain.py --source 1 --pathtoapk /Users/username/Desktop/app_to_test.apk --exploit 1`

Do you have any suggestion to solve it?

Thanks in advance

**Comment by christopher-wiko** [comment]
Running under **Mac OS X High Sierra**

My terminal output:
> JD CORE 100%|#################################################################|
> 
> Procyon  98%|###############################################################  |
> 
> CFR 100%|#####################################################################|
> 
> 
> Decompilation may hang/take too long (usually happens when the source is obfuscated).
> At any time,Press C to continue and QARK will attempt to run SCA on whatever was decompiled.
> 
> INFO - Trying to improve accuracy of the decompiled files
> INFO - Restored 102 file(s) out of 116 corrupt file(s)
> INFO - Decompiled code found at:/Users/username/Desktop/app_to_test/
> INFO - Finding all java files
> INFO - Finding all xml files
> INFO - Running Static Code Analysis...
> INFO - Looking for private key files in project
> 
> 
> User created permissions100%|#################################################|
> 
> Dynamically loading code 65%|###############################                  |
> 
> Detect exposed logs 68%|####################################                  |
> 
> External Storage Issues 68%|##################################                |
> 
> Manifest File Checks100%|#####################################################|
> 
> Webview Issues 68%|########################################                   |
> 
> Phone identifier access100%|##################################################|
> 
> Hardcoded HTTP url 71%|#######################################                |
> 
> Insecure functions100%|#######################################################|
> 
> Task Hijacking 69%|########################################                   |
> 
> Hardcoded API Keys100%|#######################################################|
> 
> Access Control Checks 70%|####################################                |
> 
> Crypto issues 63%|#####################################                       |
> 
> Broadcast issues100%|#########################################################|
> 
> Webview checks100%|###########################################################|
> 
> X.509 Validation 58%|#################################                        |
> 
> Pending Intents 47%|###########################                               |
> 
> File Permissions (check 1)100%|###############################################|
> 
> File Permissions (check 2) 82%|######################################         |

**Comment by nwalsh1995** [comment]
I imagine this is due to one of the checks/plugins running infinitely on the decompiled code of your APK. Something small that you might be able to do is use `Control-C` to try to get the python stack trace of where you have exited the program. This can point to the general area/file.

You can step through a debugger to find the real cause, if you want to drop the APK I can do that part for you.

**Comment by theforcedk** [comment]
+1

**Comment by nwalsh1995** [comment]
@theforcedk that is not surprising as there are a lot of blanket `Except:` statements that will catch Control-C.

If it is urgent I would suggest anyone having this issue to use the `v2` branch that we are working on. There is a command line available that has many of the checks that QARK has in a much better and stable manner.

Most likely this will not be fixed in master until progress on `v2` has finished and `v2` becomes the new master.

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
