### ISSUE TITLE
SDK file

### ISSUE THREAD

**Issue by A-AFTAHI** [linkedin/qark#186]
hi, can anyone help me with this issue. qark throw lots of warning when i run and when i press to Download the SDK file it shows error and refuse to download it i guess there is a problem with the path of the download source or something.
here is what my screen looks like:
  Do you want QARK to download and set up Android SDK?[y/n] :y
[##########] 100%\nFile downloaded to/root/Downloads/qark/qark/android-sdk_r24.3.4-linux.tgz
\nUnpacking  Android SDK Manager.../root/Downloads/qark/qark/android-sdk_r24.3.4-linux.tgz
/root/Downloads/qark/qark/android-sdk_r24.3.4-linux.tgz
Updated config value:: AndroidSDKPath /root/Downloads/qark/qark/android-sdk_r24.3.4-linux/android-sdk-linux/
2,25,48,184
Traceback (most recent call last):
  File "qarkMain.py", line 1281, in <module>
    nonAutomatedParseArgs()
  File "qarkMain.py", line 462, in nonAutomatedParseArgs
    main()
  File "qarkMain.py", line 574, in main
    sdkManager.get_android_sdk_manager()
  File "/root/Downloads/qark/qark/modules/sdkManager.py", line 50, in get_android_sdk_manager
    download_sdk()
  File "/root/Downloads/qark/qark/modules/sdkManager.py", line 139, in download_sdk
    run_sdk_manager()
  File "/root/Downloads/qark/qark/modules/sdkManager.py", line 173, in run_sdk_manager
    p1.stdin.write(common.args.acceptterms)
TypeError: argument 1 must be string or buffer, not None

**Comment by nwalsh1995** [comment]
Hi @A-AFTAHI , we are recommending users to use the v2 branch. Please checkout that branch and run `pip install .` in its directory, then simply the command `qark` to run. We believe that branch to be far more stable and overall better than the master branch.

It is still in its development which is why it is not the new 'master'. However, it properly mimics most of the functionality from the original QARK. v2 also requires the user to specify a path to their SDK if they want to generate the exploit APK, so this problem should not be in v2.

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
