### ISSUE TITLE
v2 version of qark can not download dex2jar tool

### ISSUE THREAD

**Issue by agap** [linkedin/qark#210]
I'm on the latest version of qark (commit `5afbac87d8fe9ed5ac84b94673b69f40cb16ffde`), when I'm trying to run the following command:

`qark --apk ~/path/to/app.apk`

I get the following result:

`Decompiling...  
Failed to download dex2jar jar
`
My idea was that for some reason qark can not download dex2jar, so if I download dex2jar manually, unzip it and put its content into the `qark/lib/dex2jar-2.0/` - everything will run smoothly.

For some reason I was wrong - even if I have all jars and sh files from dex2jar archive, qark can not be started.

**Comment by nwalsh1995** [comment]
Also, it is kind of confusing since we are installing with pip it will install into your virtualenv or where your python is located.

From that path is you place the downloaded dex2jar file into the `lib/dex2jar-2.0` path and ensure `lib/dex2jar-2.0/d2j-dex2jar.sh` exists, then it will skip the download.

**Comment by agap** [comment]
Hey, @nwalsh1995, sorry for the late reply. 

Strangely, the issue disappeared once I found the qark's installation folder, removed everything from there and then performed `pip install .` from within my local copy of qark's repo. Probably this has been somehow related to the fact that I tried to install qark v1 first and then decided to switch to v2 - maybe there is some issue in migration. Anyway, I'm closing it as I don't experience that issue anymore.
