### ISSUE TITLE
ProGuard obfuscating - performance

### ISSUE THREAD

**Issue by Patryck95** [linkedin/qark#223]
Hi,
I've read the documentation about your tool and I have a question:
If I have an APK that has some of its code obfuscated by ProGuard, can your tool still make reverse engineering on it? Because I have tried that with an APK and it takes too long, actually it seems that it begins a loop.

So was this a problem or does this tool can't actually make static analysis on a ProGuard obfuscated APK?   

Thanks

**Comment by nwalsh1995** [comment]
You are going to see a lot worse performance on obfuscated code. AFAIK there should be no infinite loops (on v2 branch), but it will take a long time to run due to the increased amount of files and code in general.

QARK is meant to be run on your own applications before obfuscation, I do not believe we will support obfuscated code any time soon. However, there is definitely room for performance improvements in the QARK code, which we try to address.
