### ISSUE TITLE
Skip decompilation?

### ISSUE THREAD

**Issue by H4oK3** [linkedin/qark#250]
It would be better if certain stage can be skipped such as decompilation; is there a way the app can resume from what already finished and skip the finished stages?

e.g. The app is not stable, it hangs at finishing static analysis, if I exit and restart the app it would start over doing all those stuff again. That would be too much overhead I think.

**Comment by nwalsh1995** [comment]
Hi @H4oK3, we are aware that the main branch is unstable. We have rewritten QARK in a much better and more stable manner in the v2 branch. Because the branch isn't fully complete yet, it hasn't been merged into the master.

Please check out the v2 branch and install it with `pip install . --user` and then try the new `qark` command line. 

Both versions have skipping APK decompilation though, in v2 it is done by passing `--java <path-to-folder-or-file>`

**Comment by H4oK3** [comment]
Thanks for reply, but are you sure it is --java? I just cloned v2 but it is unrecongnized, also which folder should I pass in as the argument?

**Comment by nwalsh1995** [comment]
Yep, its `--java`. If yours is different im guessing you didn't install it correctly. The folder you should pass in should be the folder of the decompiled APK.

**Comment by dmarjanovic** [comment]
@nwalsh1995 when running `pip install . --user` I get error:

> can't copy 'qark/ate/var/folders/c4/ths6f2ms0g11wf17tcmsjnbshl_34s/T/pip-req-build-H65A3O/qark/lib/decompilers/jd-core-java-1.2.jar': doesn't exist or not a regular file

Any idea? Thanks
