### ISSUE TITLE
error while creating the custome expolit apk

### ISSUE THREAD

**Issue by saleem144** [linkedin/qark#41]
![error-quark-custome-apk-exploit](https://cloud.githubusercontent.com/assets/5344126/15956815/a5c2d02a-2f08-11e6-9f76-2116fd34b0ff.PNG)

Any package is missed ? 
Guide me for resolving this error !

**Comment by SecBro1** [comment]
This appears to be a result of the Android SDK version installed on your machine that QARK is configured to use. 

You can find how to resolve this issue here: http://stackoverflow.com/questions/32664923/unable-to-compile-my-android-project

Alternatively, if you delete and re-download QARK, it should fix it as well, if you choose to download the Android SDK.
