### ISSUE TITLE
Few suggestions - Gradle project

### ISSUE THREAD

**Issue by alipov** [linkedin/qark#7]
To analyze a gradle project (sources) with many modules (libs), I have to manually pick a manifest for each module. Can you automate this task (scan all the project modules)?

Also, consider to stop suggesting manifests beneath <modulename>/build/intermediates folders - currently it creates too much noise.

**Comment by SecBro1** [comment]
Alex, I believe your first concern is already on our informal roadmap, but we appreciate the feedback none-the-less. It is important to us to know what people using QARK want to see prioritized. We will discuss it and update this thread once we have a plan of action. To be 100% effective, it seems we need to basically emulate the build process in QARK, so we can have an accurate picture of what will go into the APK and this is going to take some time. Please understand this may not be immediate as we are already committed to a few other improvements.

When building QARK we felt the compromise here would be that people could scan their built APK if they wanted to include all the libraries, although we realize there are some limitations due to the imperfect nature of the decompilers.

The second issue you raise sounds much easier to address. We'll discuss this and should have an answer on that quickly.

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
